aws:
  key: 'AKIAIGTHLNTR6RLD56IA'
  secret: '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'

twitter:
  api_token: '4GKhV6IgDLyKhirFRomfA'
  api_secret: 'OzOExHdFFBRQ0V3n0avnjQm5IylJ6TL9K3iLLtWd7Y'
  apigee: 'no' 


